services:

  database:
    image: mariadb
    container_name: vuelosdb
    ports:
      - "3306:3306"
    volumes:
      - SENA-SOFT:/var/lib/mysql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
      - MARIADB_DATABASE=GESTION_VUELOS

  backend:
    build:
      context: ./Backend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./Frontend
      dockerfile: DockerFile
    ports:
      - "8088:80"
    # volumes:
    #   - ./Frontend/public:/usr/share/nginx/html:ro
    environment:
      - NODE_ENV=development
      

volumes:
  SENA-SOFT:
