#Imagen de node
FROM node

#directorio de trabajo en el contenedor
WORKDIR /app

#Copiar los archivos de dependecias 
COPY package.json package-lock.json ./

#Instalar dependencias
RUN npm install

#Copiar todo el proyecto
COPY . .

#usar puerto 3000
EXPOSE 3000

CMD ["npm", "run", "start"]